name: R&D budget
issue_type: compatible
descriptions:
  - You have to negotiate the annual R&D budget for the joint venture. A higher budget leads to a better product for both companies.
  - You have to negotiate the annual R&D budget for the joint venture. A higher budget leads to a better product for both companies.
payoffs:
  - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
payoff_labels:
  - ["$0", "$1M", "$2M", "$3M", "$4M", "$5M", "$6M", "$7M", "$8M", "$9M", "$10M"]
  - ["$0", "$1M", "$2M", "$3M", "$4M", "$5M", "$6M", "$7M", "$8M", "$9M", "$10M"]