name: revenue split
issue_type: distributive
descriptions:
  - You have to negotiate what percentage of the joint venture's revenue your company will receive.
  - You have to negotiate what percentage of the joint venture's revenue your company will receive.
payoffs:
  - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
payoff_labels:
  - ["25%", "30%", "35%", "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%"]
  - ["25%", "30%", "35%", "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%"]